spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace